django_practice/urls.py
from django.urls import path

from . import views

app_name = 'grocerylist'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:groceryitem_id>/', views.groceryitem, name='viewgroceryitem'),
	# /grocerylist/register
	path('register', views.register, name="register"),
	# /grocerylist/change_password
	path('change_password', views.change_password, name='change_password'),
	# /grocerylist/login
	path('login', views.login_view, name='login'),
	# /grocerylist/logout
	path('logout', views.logout_view, name="logout"),
	# /grocerylist/add_item
	path('add_item', views.add_item, name='add_item'),
	# /grocerylist/<groceryitem_id>/edit
	path('<int:groceryitem_id>/edit', views.update_item, name='update_item'),
	# /grocerylist/<groceryitem_id>/delete
	path('<int:groceryitem_id>/delete', views.delete_item, name='delete_item'),
]

s01_Activity/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

django_practice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class GroceryItem(models.Model):
	item_name = models.CharField(max_length=50)
	category = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

django_practice/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddItemForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)

class UpdateItemForm(forms.Form):
	item_name = forms.CharField(label='Item Name', max_length=50)
	category = forms.CharField(label='Category', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import GroceryItem
from .forms import LoginForm, AddItemForm, UpdateItemForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

# Create your views here.
def index(request):
	groceryitem_list = GroceryItem.objects.filter(user_id=request.user.id)
	context = {
		'groceryitem_list': groceryitem_list,
		'user': request.user
	}
	return render(request, "grocerylist/index.html", context)

def groceryitem(request, groceryitem_id):
	groceryitem = get_object_or_404(GroceryItem, pk=groceryitem_id)
	return render(request, "grocerylist/groceryitem.html", model_to_dict(groceryitem))

def register(request):
	users = User.objects.all()
	is_user_registered = False
	context = {
		"is_user_registered": is_user_registered
	}

	for indiv_user in users:
		if indiv_user.username == "johndoe":
			is_user_registered = True
			break


	if is_user_registered == False:
		user = User()
		user.username = "janedoe"
		user.first_name = "Jane"
		user.last_name = "Doe"
		user.email = "jane@mail.com"
		user.set_password("jane1234")
		user.is_staff = False
		user.is_active = True
		user.save()
		context ={
			"first_name": user.first_name,
			"last_name": user.last_name
		}

	return render(request, "grocerylist/register.html", context)

def change_password(request):

	is_user_authenticated = False

	user = authenticate(username="johndoe", password="john1234")
	print(user)
	if user is not None:
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True
		context = {
			"is_user_authenticated": is_user_authenticated
		}

		return render(request, "grocerylist/change_password.html", context)

def login_view(request):
	context = {}

	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

			if user is not None:
				login(request, user)
				return redirect("grocerylist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "grocerylist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("grocerylist:index")

def add_item(request):
	context = {
       "user": request.user
    }

	if request.method == 'POST':
		form = AddItemForm(request.POST)

		if form.is_valid() == False:
			form = AddItemForm()
		else:
			item_name = form.cleaned_data['item_name']
			category = form.cleaned_data['category']

			duplicates = GroceryItem.objects.filter(item_name=item_name)

			if not duplicates:
				GroceryItem.objects.create(item_name=item_name, category=category, date_created=timezone.now(), user_id=request.user.id)
				return redirect('grocerylist:index')

			else:
				context = {
					"error": True
				}

	return render(request, "grocerylist/add_item.html", context)


def update_item(request, groceryitem_id):

	groceryitem = GroceryItem.objects.filter(pk=groceryitem_id)

	context = {
		"user": request.user,
		"groceryitem_id": groceryitem_id,
		"item_name": groceryitem[0].item_name,
		"category": groceryitem[0].category,
		"status": groceryitem[0].status
	}

	if request.method == 'POST':
		form = UpdateItemForm(request.POST)

		if form.is_valid() == False:
			form = UpdateItemForm()
		else:
			item_name = form.cleaned_data['item_name']
			category = form.cleaned_data['category']
			status = form.cleaned_data['status']

			if groceryitem:
				groceryitem[0].item_name = item_name
				groceryitem[0].category = category
				groceryitem[0].status = status

				groceryitem[0].save()
				return redirect("grocerylist:index")
			else:
				context = {
					"error": True
				}

	return render(request, "grocerylist/update_item.html", context)

def delete_item(request, groceryitem_id):
	groceryitem = GroceryItem.objects.filter(pk=groceryitem_id).delete()
	return redirect("grocerylist:index")

django_practice/templates/grocerylist/add_item.html
{% extends 'base.html' %}

{% block title %}Add Item{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add Item</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate item found</p>
				{% endif %}
				<form action="{% url 'grocerylist:add_item' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="item_name">Item Name: </label>
					    <input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
					    <label for="category">Category: </label>
					    <textarea class="form-control" name="category" value="{{ category }}" required></textarea>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Add Item">
					</div>

				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1>You are not authorized to access this page.</h1>
		<p>Kindly login <a href="{% url 'grocerylist:login'%}">here</a></p>
	{% endif %}
{% endblock %}

django_practice/templates/grocerylist/change_password.html
{% if is_user_authenticated == False %} 
	<h1>Invalid User Credentials!</h1>
	<p>Check if the username and password is correct</p>
{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated.</p>
{% endif %}

django_practice/templates/grocerylist/groceryitem.html
{% extends 'base.html' %}

{% block title %}Update{% endblock %}

{% block content%}
	<div class="text-center my-3">
		<h1>{{ item_name }}</h1>
		<h3>category</h3>
		<p>{{ category }}</p>
		<h3>Status</h3>
		<p>{{ status }}</p>
		
		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'grocerylist:update_item' id %}" class="text-light text-decoration-none">Edit Item</a>
		</button>

		<button class="btn btn-danger mx-1 text-decoration-none">
			<a href="{% url 'grocerylist:delete_item' id %}" class="text-light text-decoration-none">Delete Item</a>
		</button>

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'grocerylist:index' %}" class="text-light text-decoration-none">Back To Items</a>
		</button>
		
	</div>
{% endblock %}

django_practice/templates/grocerylist/index.html
{% extends 'base.html'%}

{% block title %}Home{% endblock %}

{% block content%}
    {% if groceryitem_list and user.is_anonymous == False  %}
        <h1 class="text-center my-3">Welcome {{ user.first_name }} {{user.last_name}}!</h1>
        <div class="container">
            <div class="row">
                <h3 class="text-center mb-3">My Tasks</h3>
                <ul class="list-group col-lg-2 offset-lg-5 text-center">
                {% for groceryitem in groceryitem_list %}
                    <a href="{% url 'grocerylist:viewgroceryitem' groceryitem.id %}" class="text-decoration-none">
                        <li class="list-group-item">{{ groceryitem.task_name }}</li>
                    </a>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% elif user.is_anonymous == True %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'grocerylist:login' %}">here</a></p>
    {% else %}
        <p class="text-center">No items has been created</p>
    {% endif %}
{% endblock%}

django_practice/templates/grocerylist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock%}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Login</h1>
				{% if error == True %}
					<p class="text-danger">Invalid user credentials, please check your username and password</p>
				{% endif %}
				<form action="{% url 'grocerylist:login' %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
					    <label for="username">Username: </label>
					    <input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
					</div>

					<div class="mb-3">
					    <label for="password">Password: </label>
					    <input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
					</div>

					<div class="text-center">
				    	<input class="btn btn-success" type="submit" value="Login">
					</div>

				</form>
			</div>
		</div>
	</div>

{% endblock %}

django_practice/templates/grocerylist/register.html
{% if is_user_registered == False %}
	<h1>Duplicate User Found</h1>
	<p>A duplicate user has been found, user creation unsuccessful</p>
{% else %}
	<h1>User Successfully Created!</h1>
	<p>The account for {{first_name}} {{last_name}} has been successfully created</p>
{% endif %}

django_practice/templates/grocerylist/update_item.html
{% extends 'base.html' %}

{% block title %}Update Item{% endblock %}

{% block content%}
	{% if user.is_anonymous == False%}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center my-3">Update Item</h1>
					{% if error == True %}
						<p class="text-danger">Item not found</p>
					{% endif %}
					<form action="{% url 'grocerylist:update_item' groceryitem_id %}" method="post">
						{% csrf_token %}

						<div class="mb-3">
						    <label for="item_name">Item Name: </label>
						    <input class="form-control" id="item_name" type="text" name="item_name" value="{{ item_name }}" maxlength="50" required>
						</div>

						<div class="mb-3">
						    <label for="category">Category: </label>
						    <textarea class="form-control" name="category" required>{{ category }}</textarea>
						</div>

						<div class="mb-3">
						    <label for="status">Status: </label>
						    <input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
						</div>

						<div class="text-center">
					    	<input class="btn btn-success" type="submit" value="Update Item">
						</div>

					</form>
				</div>
			</div>
		</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'grocerylist:login' %}">here</a></p>
	{% endif %}
{% endblock%}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}To Do App{% endblock%}</title>

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
<body>
	{% include "navbar.html" %}

	{% block content%}
	{% endblock %}

	<!-- Bootstrap -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">To Do App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="add_item">Add Item</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="register">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logout">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>